export const listings = [
  {
    id_extern: "104305427",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 198000,
    currency: "EUR",
    zone: "Buiucani",
    m2: 116,
    rooms: 3,
    floor: 3,
  },
  {
    id_extern: "104981741",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Periferie,  Durlești,  Chișinău mun.",
    price: 113946,
    currency: "EUR",
    zone: "Periferie",
    m2: 81,
    rooms: 2,
    floor: 1,
  },
  {
    id_extern: "104911037",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Telecentru,  Chișinău,  Chișinău mun.",
    price: 119900,
    currency: "EUR",
    zone: "Telecentru",
    m2: 50,
    rooms: 2,
    floor: 8,
  },
  {
    id_extern: "104945499",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 150000,
    currency: "EUR",
    zone: "Botanica",
    m2: 85,
    rooms: 3,
    floor: 10,
  },
  {
    id_extern: "105099159",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 148900,
    currency: "EUR",
    zone: "Ciocana",
    m2: 80,
    rooms: 3,
    floor: 3,
  },
  {
    id_extern: "78392686",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 60,
    currency: "EUR",
    zone: "Centru",
    m2: 65,
    rooms: 2,
    floor: 10,
  },
  {
    id_extern: "104156591",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 59900,
    currency: "EUR",
    zone: "Ciocana",
    m2: 34,
    rooms: 1,
    floor: 9,
  },
  {
    id_extern: "104708884",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 172000,
    currency: "EUR",
    zone: "Buiucani",
    m2: 68,
    rooms: 2,
    floor: 2,
  },
  {
    id_extern: "78392490",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 1 cameră,  Centru,  Chișinău,  Chișinău mun.",
    price: 60,
    currency: "EUR",
    zone: "Centru",
    m2: 65,
    rooms: 1,
    floor: 10,
  },
  {
    id_extern: "103870655",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 71900,
    currency: "EUR",
    zone: "Ciocana",
    m2: 59,
    rooms: 3,
    floor: 4,
  },
  {
    id_extern: "104769725",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 159999,
    currency: "EUR",
    zone: "Botanica",
    m2: 83,
    rooms: 2,
    floor: 8,
  },
  {
    id_extern: "105048154",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 3 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 600,
    currency: "EUR",
    zone: "Ciocana",
    m2: 70,
    rooms: 3,
    floor: 1,
  },
  {
    id_extern: "105100182",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 2 camere,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 450,
    currency: "EUR",
    zone: "Râșcani",
    m2: 58,
    rooms: 2,
    floor: 8,
  },
  {
    id_extern: "105100189",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Telecentru,  Chișinău,  Chișinău mun.",
    price: 70000,
    currency: "EUR",
    zone: "Telecentru",
    m2: 34,
    rooms: 1,
    floor: 2,
  },
  {
    id_extern: "104029484",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Botanica,  Chișinău,  Chișinău mun.",
    price: 61200,
    currency: "EUR",
    zone: "Botanica",
    m2: 36,
    rooms: 1,
    floor: 4,
  },
  {
    id_extern: "103623906",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 76500,
    currency: "EUR",
    zone: "Botanica",
    m2: 41,
    rooms: 2,
    floor: 2,
  },
  {
    id_extern: "103199679",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Centru,  Orhei,  Orhei",
    price: 99900,
    currency: "EUR",
    zone: "Centru",
    m2: 68,
    rooms: 2,
    floor: 2,
  },
  {
    id_extern: "103623980",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 225000,
    currency: "EUR",
    zone: "Buiucani",
    m2: 92,
    rooms: 3,
    floor: 1,
  },
  {
    id_extern: "104123787",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 130000,
    currency: "EUR",
    zone: "Ciocana",
    m2: 54,
    rooms: 2,
    floor: 7,
  },
  {
    id_extern: "87171624",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 1 cameră,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 650,
    currency: "MDL",
    zone: "Râșcani",
    m2: 51,
    rooms: 1,
    floor: 5,
  },
  {
    id_extern: "104810093",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Centru,  Durlești,  Chișinău mun.",
    price: 95500,
    currency: "EUR",
    zone: "Centru",
    m2: 65,
    rooms: 2,
    floor: 9,
  },
  {
    id_extern: "105063776",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Telecentru,  Chișinău,  Chișinău mun.",
    price: 245000,
    currency: "EUR",
    zone: "Telecentru",
    m2: 80,
    rooms: 2,
    floor: 6,
  },
  {
    id_extern: "104760039",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Periferie,  Durlești,  Chișinău mun.",
    price: 57500,
    currency: "EUR",
    zone: "Periferie",
    m2: 47,
    rooms: 1,
    floor: 3,
  },
  {
    id_extern: "105100177",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Centru,  Durlești,  Chișinău mun.",
    price: 142500,
    currency: "EUR",
    zone: "Centru",
    m2: 71,
    rooms: 2,
    floor: 7,
  },
  {
    id_extern: "102396857",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 1 cameră,  Telecentru,  Chișinău,  Chișinău mun.",
    price: 550,
    currency: "MDL",
    zone: "Telecentru",
    m2: 50,
    rooms: 1,
    floor: 1,
  },
  {
    id_extern: "105032724",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 129500,
    currency: "EUR",
    zone: "Botanica",
    m2: 72,
    rooms: 3,
    floor: 2,
  },
  {
    id_extern: "103549563",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 205000,
    currency: "EUR",
    zone: "Centru",
    m2: 83,
    rooms: 2,
    floor: 10,
  },
  {
    id_extern: "104959019",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Periferie,  Durlești,  Chișinău mun.",
    price: 44000,
    currency: "EUR",
    zone: "Periferie",
    m2: 43,
    rooms: 1,
    floor: 3,
  },
  {
    id_extern: "103964585",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 85833,
    currency: "EUR",
    zone: "Râșcani",
    m2: 43,
    rooms: 1,
    floor: 5,
  },
  {
    id_extern: "105063690",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 258000,
    currency: "EUR",
    zone: "Centru",
    m2: 79,
    rooms: 2,
    floor: 6,
  },
  {
    id_extern: "103934636",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 92000,
    currency: "EUR",
    zone: "Buiucani",
    m2: 45,
    rooms: 1,
    floor: 7,
  },
  {
    id_extern: "103754944",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 175000,
    currency: "EUR",
    zone: "Buiucani",
    m2: 71,
    rooms: 2,
    floor: 1,
  },
  {
    id_extern: "103677788",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 119900,
    currency: "EUR",
    zone: "Ciocana",
    m2: 72,
    rooms: 2,
    floor: 8,
  },
  {
    id_extern: "82814773",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 1 cameră,  Centru,  Chișinău,  Chișinău mun.",
    price: 800,
    currency: "MDL",
    zone: "Centru",
    m2: 50,
    rooms: 1,
    floor: 5,
  },
  {
    id_extern: "88729657",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 4 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 2800,
    currency: "EUR",
    zone: "Centru",
    m2: 150,
    rooms: 4,
    floor: 4,
  },
  {
    id_extern: "104798615",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 158250,
    currency: "EUR",
    zone: "Râșcani",
    m2: 53,
    rooms: 2,
    floor: 1,
  },
  {
    id_extern: "102683548",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 1300,
    currency: "EUR",
    zone: "Centru",
    m2: 65,
    rooms: 2,
    floor: 9,
  },
  {
    id_extern: "83346554",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 800,
    currency: "EUR",
    zone: "Centru",
    m2: 96,
    rooms: 2,
    floor: 6,
  },
  {
    id_extern: "101491395",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 1 cameră,  Centru,  Chișinău,  Chișinău mun.",
    price: 600,
    currency: "MDL",
    zone: "Centru",
    m2: 20,
    rooms: 1,
    floor: null,
  },
  {
    id_extern: "104375779",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 1400,
    currency: "EUR",
    zone: "Centru",
    m2: 70,
    rooms: 2,
    floor: 5,
  },
  {
    id_extern: "104723288",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 148000,
    currency: "EUR",
    zone: "Buiucani",
    m2: 72,
    rooms: 3,
    floor: 3,
  },
  {
    id_extern: "104328901",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 270000,
    currency: "EUR",
    zone: "Centru",
    m2: 91,
    rooms: 2,
    floor: 6,
  },
  {
    id_extern: "104477136",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 3 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 1000,
    currency: "EUR",
    zone: "Centru",
    m2: 87,
    rooms: 3,
    floor: 4,
  },
  {
    id_extern: "101366181",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 219000,
    currency: "EUR",
    zone: "Centru",
    m2: 82,
    rooms: 3,
    floor: 10,
  },
  {
    id_extern: "105087650",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Centru,  Durlești,  Chișinău mun.",
    price: 108900,
    currency: "EUR",
    zone: "Centru",
    m2: 48,
    rooms: 1,
    floor: 2,
  },
  {
    id_extern: "101821456",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 217000,
    currency: "EUR",
    zone: "Râșcani",
    m2: 155,
    rooms: 3,
    floor: 16,
  },
  {
    id_extern: "101751856",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 800,
    currency: "EUR",
    zone: "Centru",
    m2: 55,
    rooms: 2,
    floor: 1,
  },
  {
    id_extern: "102575667",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 3 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 1500,
    currency: "EUR",
    zone: "Centru",
    m2: 150,
    rooms: 3,
    floor: 6,
  },
  {
    id_extern: "104901899",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 73000,
    currency: "EUR",
    zone: "Râșcani",
    m2: 32,
    rooms: 1,
    floor: 2,
  },
  {
    id_extern: "103697954",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Telecentru,  Chișinău,  Chișinău mun.",
    price: 93400,
    currency: "EUR",
    zone: "Telecentru",
    m2: 52,
    rooms: 2,
    floor: 2,
  },
  {
    id_extern: "104882054",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 850,
    currency: "EUR",
    zone: "Centru",
    m2: 72,
    rooms: 2,
    floor: 7,
  },
  {
    id_extern: "105083570",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 145000,
    currency: "EUR",
    zone: "Ciocana",
    m2: 55,
    rooms: 2,
    floor: 1,
  },
  {
    id_extern: "103147365",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Centru,  Durlești,  Chișinău mun.",
    price: 57200,
    currency: "EUR",
    zone: "Centru",
    m2: 44,
    rooms: 1,
    floor: 9,
  },
  {
    id_extern: "104723965",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 1 cameră,  Centru,  Chișinău,  Chișinău mun.",
    price: 600,
    currency: "MDL",
    zone: "Centru",
    m2: 20,
    rooms: 1,
    floor: 2,
  },
  {
    id_extern: "104876256",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Sculeni,  Chișinău,  Chișinău mun.",
    price: 64000,
    currency: "EUR",
    zone: "Sculeni",
    m2: 41,
    rooms: 1,
    floor: 9,
  },
  {
    id_extern: "88313196",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 2 camere,  Telecentru,  Chișinău,  Chișinău mun.",
    price: 400,
    currency: "EUR",
    zone: "Telecentru",
    m2: 40,
    rooms: 2,
    floor: 2,
  },
  {
    id_extern: "105100160",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 120000,
    currency: "EUR",
    zone: "Botanica",
    m2: 68,
    rooms: 3,
    floor: 4,
  },
  {
    id_extern: "103625301",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 221500,
    currency: "EUR",
    zone: "Buiucani",
    m2: 105,
    rooms: 3,
    floor: 8,
  },
  {
    id_extern: "104558750",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 447000,
    currency: "EUR",
    zone: "Centru",
    m2: 123,
    rooms: 3,
    floor: null,
  },
  {
    id_extern: "104694152",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 124500,
    currency: "EUR",
    zone: "Ciocana",
    m2: 71,
    rooms: 2,
    floor: 3,
  },
  {
    id_extern: "104359788",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 3 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 1399,
    currency: "EUR",
    zone: "Centru",
    m2: 85,
    rooms: 3,
    floor: 4,
  },
  {
    id_extern: "105098257",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 87000,
    currency: "EUR",
    zone: "Ciocana",
    m2: 37,
    rooms: 1,
    floor: 9,
  },
  {
    id_extern: "103778751",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 3 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 1299,
    currency: "EUR",
    zone: "Ciocana",
    m2: 110,
    rooms: 3,
    floor: 19,
  },
  {
    id_extern: "104254274",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Centru,  Orhei,  Orhei",
    price: 169000,
    currency: "EUR",
    zone: "Centru",
    m2: 113,
    rooms: 3,
    floor: 9,
  },
  {
    id_extern: "105024244",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 193000,
    currency: "EUR",
    zone: "Botanica",
    m2: 64,
    rooms: 2,
    floor: 12,
  },
  {
    id_extern: "104537043",
    offer_type: "Vând",
    title: "O cameră,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 42900,
    currency: "EUR",
    zone: "Ciocana",
    m2: 23,
    rooms: null,
    floor: 9,
  },
  {
    id_extern: "104969949",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 270000,
    currency: "EUR",
    zone: "Râșcani",
    m2: 111,
    rooms: 3,
    floor: 3,
  },
  {
    id_extern: "105088083",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 171900,
    currency: "EUR",
    zone: "Centru",
    m2: 72,
    rooms: 2,
    floor: 2,
  },
  {
    id_extern: "104971148",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Telecentru,  Chișinău,  Chișinău mun.",
    price: 28900,
    currency: "EUR",
    zone: "Telecentru",
    m2: 28,
    rooms: 1,
    floor: 8,
  },
  {
    id_extern: "102820138",
    offer_type: "Vând",
    title: "Apartament cu 4 camere,  Poșta Veche,  Chișinău,  Chișinău mun.",
    price: 149900,
    currency: "EUR",
    zone: "Poșta Veche",
    m2: 100,
    rooms: 4,
    floor: 10,
  },
  {
    id_extern: "103006282",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 158000,
    currency: "EUR",
    zone: "Ciocana",
    m2: 77,
    rooms: 2,
    floor: 11,
  },
  {
    id_extern: "100924192",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 74250,
    currency: "EUR",
    zone: "Râșcani",
    m2: 45,
    rooms: 1,
    floor: 6,
  },
  {
    id_extern: "105100146",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 67000,
    currency: "EUR",
    zone: "Ciocana",
    m2: 40,
    rooms: 1,
    floor: 9,
  },
  {
    id_extern: "104754426",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 165000,
    currency: "EUR",
    zone: "Buiucani",
    m2: 89,
    rooms: 2,
    floor: 5,
  },
  {
    id_extern: "104040411",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 278000,
    currency: "EUR",
    zone: "Centru",
    m2: 70,
    rooms: 2,
    floor: 3,
  },
  {
    id_extern: "104536976",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 124000,
    currency: "EUR",
    zone: "Ciocana",
    m2: 73,
    rooms: 3,
    floor: 7,
  },
  {
    id_extern: "104621227",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 95110,
    currency: "EUR",
    zone: "Râșcani",
    m2: 63,
    rooms: 2,
    floor: 13,
  },
  {
    id_extern: "104416151",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 90000,
    currency: "EUR",
    zone: "Râșcani",
    m2: 67,
    rooms: 2,
    floor: 3,
  },
  {
    id_extern: "103655917",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 179500,
    currency: "EUR",
    zone: "Buiucani",
    m2: 70,
    rooms: 2,
    floor: 6,
  },
  {
    id_extern: "102632780",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Telecentru,  Chișinău,  Chișinău mun.",
    price: 84375,
    currency: "EUR",
    zone: "Telecentru",
    m2: 56,
    rooms: 2,
    floor: 7,
  },
  {
    id_extern: "104968141",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 1 cameră,  Centru,  Chișinău,  Chișinău mun.",
    price: 550,
    currency: "EUR",
    zone: "Centru",
    m2: 50,
    rooms: 1,
    floor: 9,
  },
  {
    id_extern: "104801885",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 250000,
    currency: "EUR",
    zone: "Ciocana",
    m2: 82,
    rooms: 2,
    floor: 13,
  },
  {
    id_extern: "105089985",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 118000,
    currency: "EUR",
    zone: "Botanica",
    m2: 46,
    rooms: 2,
    floor: 7,
  },
  {
    id_extern: "105088048",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 149500,
    currency: "EUR",
    zone: "Ciocana",
    m2: 87,
    rooms: 3,
    floor: 4,
  },
  {
    id_extern: "104883003",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 1 cameră,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 1200,
    currency: "EUR",
    zone: "Râșcani",
    m2: 60,
    rooms: 1,
    floor: 11,
  },
  {
    id_extern: "100947271",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Durlești,  Chișinău,  Chișinău mun.",
    price: 58295,
    currency: "EUR",
    zone: "Centru",
    m2: 45,
    rooms: 1,
    floor: 2,
  },
  {
    id_extern: "104659566",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Poșta Veche,  Chișinău,  Chișinău mun.",
    price: 79000,
    currency: "EUR",
    zone: "Poșta Veche",
    m2: 42,
    rooms: 2,
    floor: 2,
  },
  {
    id_extern: "105100132",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 107900,
    currency: "EUR",
    zone: "Buiucani",
    m2: 60,
    rooms: 2,
    floor: 5,
  },
  {
    id_extern: "103690519",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 127100,
    currency: "EUR",
    zone: "Buiucani",
    m2: 82,
    rooms: 3,
    floor: 6,
  },
  {
    id_extern: "103581622",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 77550,
    currency: "EUR",
    zone: "Ciocana",
    m2: 55,
    rooms: 1,
    floor: 9,
  },
  {
    id_extern: "103433266",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 2 camere,  Centru,  Chișinău,  Chișinău mun.",
    price: 50,
    currency: "EUR",
    zone: "Centru",
    m2: 52,
    rooms: 2,
    floor: 3,
  },
  {
    id_extern: "101203714",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 124000,
    currency: "EUR",
    zone: "Ciocana",
    m2: 50,
    rooms: 2,
    floor: 20,
  },
  {
    id_extern: "102390002",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 92000,
    currency: "EUR",
    zone: "Buiucani",
    m2: 50,
    rooms: 1,
    floor: 7,
  },
  {
    id_extern: "103639786",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 167000,
    currency: "EUR",
    zone: "Botanica",
    m2: 84,
    rooms: 2,
    floor: 7,
  },
  {
    id_extern: "104095044",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Centru,  Durlești,  Chișinău mun.",
    price: 97750,
    currency: "EUR",
    zone: "Centru",
    m2: 85,
    rooms: 3,
    floor: 5,
  },
  {
    id_extern: "87558295",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 1 cameră,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 60,
    currency: "EUR",
    zone: "Ciocana",
    m2: 50,
    rooms: 1,
    floor: 7,
  },
  {
    id_extern: "102823304",
    offer_type: "Vând",
    title: "Apartament cu 3 camere,  Periferie,  Orhei,  Orhei",
    price: 75000,
    currency: "EUR",
    zone: "Periferie",
    m2: 63,
    rooms: 3,
    floor: 5,
  },
  {
    id_extern: "104941834",
    offer_type: "Vând",
    title: "Apartament cu 4 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 143000,
    currency: "EUR",
    zone: "Ciocana",
    m2: 97,
    rooms: 4,
    floor: 9,
  },
  {
    id_extern: "104551405",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 137500,
    currency: "EUR",
    zone: "Botanica",
    m2: 48,
    rooms: 2,
    floor: 4,
  },
  {
    id_extern: "104690157",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 184900,
    currency: "EUR",
    zone: "Buiucani",
    m2: 72,
    rooms: 2,
    floor: 4,
  },
  {
    id_extern: "104615914",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 485000,
    currency: "EUR",
    zone: "Râșcani",
    m2: 130,
    rooms: 2,
    floor: null,
  },
  {
    id_extern: "105064900",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 2 camere,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 750,
    currency: "MDL",
    zone: "Râșcani",
    m2: 45,
    rooms: 2,
    floor: 4,
  },
  {
    id_extern: "105034622",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Buiucani,  Chișinău,  Chișinău mun.",
    price: 186500,
    currency: "EUR",
    zone: "Buiucani",
    m2: 69,
    rooms: 2,
    floor: 3,
  },
  {
    id_extern: "104502679",
    offer_type: "Vând",
    title: "Apartament cu 1 cameră,  Telecentru,  Chișinău,  Chișinău mun.",
    price: 74000,
    currency: "EUR",
    zone: "Telecentru",
    m2: 49,
    rooms: 1,
    floor: 3,
  },
  {
    id_extern: "105045547",
    offer_type: "Vând",
    title: "Apartament cu 2 camere,  Botanica,  Chișinău,  Chișinău mun.",
    price: 174900,
    currency: "EUR",
    zone: "Botanica",
    m2: 74,
    rooms: 2,
    floor: 8,
  },
  {
    id_extern: "105072882",
    offer_type: "De închiriat lunar",
    title: "Apartament cu 3 camere,  Râșcani,  Chișinău,  Chișinău mun.",
    price: 1300,
    currency: "EUR",
    zone: "Râșcani",
    m2: 90,
    rooms: 3,
    floor: 9,
  },
  {
    id_extern: "86265166",
    offer_type: "De închiriat pe zi",
    title: "Apartament cu 2 camere,  Ciocana,  Chișinău,  Chișinău mun.",
    price: 50,
    currency: "EUR",
    zone: "Ciocana",
    m2: 55,
    rooms: 2,
    floor: 15,
  },
];
